### ISSUE TITLE
Classic editor addons 

### ISSUE THREAD

**Issue by mjocon** [senlin/classic-editor-addon#13]
I'm running wp 6.0 and frameworks are not responsive. 
When I select SDF builder on a page the frames show up just fine, but none of the functions work. Like edit, clone, or delete, no functionality.  Text editor is the only way that I can edit my websites.  Can there be any way to fix this issue other than trying to roll back to 5.o or lower.  My Hostgator is out of options to help me roll back that far. 
Your help would be most appreciated.
Max
559 908 9037

**Comment by senlin** [comment]
Hello Max, to be honest I have no idea what you're referring to above. SDF builder? The only functions of the Classic Editor Addon are removing the settings page of the Classic Editor plugin and removing the redundant styles and scripts the WP Block Editor loads on the frontend.
