### ISSUE TITLE
Deregister hook wrong?

### ISSUE THREAD

**Issue by adekrijger** [senlin/classic-editor-addon#14]
```	
if ( class_exists( 'woocommerce' ) ) {
	wp_dequeue_style( 'wc-block-style' );
	wp_deregister_style( 'wc-block-style' );
}
```
This does not work, because the handles should be wc-blocks-style with an s.

**Comment by senlin** [comment]
More than welcome to leave a PR

**Comment by senlin** [comment]
Yes, you were right it needs the additional "s", WooCommerce changed that fairly recently...

Just released new version that addresses this too.
