### ISSUE TITLE
Undoing the Changes that Clastic editor Plus Made Please help

### ISSUE THREAD

**Issue by Wayne0002** [senlin/classic-editor-addon#16]
Hi Peter 

I installed Clasic Editor Plus  and it seems to have affected Elementor in that when I edit a post in elementor it does not see the associated template for the post.

My question is how can I undo all the changes that the plugin made ?

Kind Regards

W Boonzaier

**Comment by senlin** [comment]
Hello Wayne, thank for you message. Are you aware that [Classic Editor Plus](https://wordpress.org/plugins/classic-editor-plus/) is a different plugin than my **Classic Editor +** (previously _Classic Editor Addon_)?

Furthermore typically plugins that disable the WP Block Editor and bring back the Classic Editor do not make any changes in templates (of other plugins). Take for example a look at [the source code of this plugin](https://github.com/senlin/classic-editor-addon/blob/master/classic-editor-addon.php#L40-L58) it only dequeues and deregisters styles.

So there is nothing it "does" in terms of making changes to Elementor templates. 

To be honest I doubt the issue you describe is related to the Classic Editor Plus or + plugin, but you can always try to deactivate and uninstall it.

**Comment by Wayne0002** [comment]
Hi Peter

Thank you for the reply.

I uninstalled it and reinstalled the classic editor and that seems to have
resolved the problem. I was using short codes in the classic editor to
render saved inersections to the post content together with elementor
global templates and the installed editor + caused the short codes not to
appear.

Best  Regards
ADV WB Boonzaier
Chambers Johannesburg
Email ***@***.***

**Comment by senlin** [comment]
Glad to hear you solved your issue!

**Comment by Wayne0002** [comment]
Hi Peter 

 

Thank you.

 

If you have time I wounder if you could point me to your plugin and its documentation and tell me a bit about what it does better than the native WP editor.

 

I hate the block editor and I am publishing articles using the standard WP editor and inserting short codes for Elementor templates to do various things. 

 

when needed which seems to be working ok at this point. Would your plugin be suitable for that.

 

 

Best Regards 

ADV WB Boonzaier   

Chambers Johannesburg

**Comment by senlin** [comment]
> If you have time I wounder if you could point me to your plugin and its documentation and tell me a bit about what it does better than the native WP editor.

The source code is [right here on Github](https://github.com/senlin/classic-editor-addon), including Readme file. If that format is not suitable for you, then you can also see the plugin on [the WP.org site](https://wordpress.org/plugins/classic-editor-addon).
