### ISSUE TITLE
WP 6.3 update - link insertion not working as expected

### ISSUE THREAD

**Issue by supportTheArtblog** [senlin/classic-editor-addon#17]
Hello, we just updated our site to 6.3 and in our visual editor the insert/edit link button no longer pops open a window to add the link url. Now it only changes the selected text blue. If you click to text editor the highlighted position remains though the words have moved. The first image shows the button clicked and the highlighted text. The 2nd image is after selecting the text editor to show it changed what is selected. Thanks for your time. 
![Screen Shot 2023-08-16 at 2 43 53 PM](https://github.com/senlin/classic-editor-addon/assets/141756083/a714de02-9805-4765-8774-fdad63f71db6)
![Screen Shot 2023-08-16 at 2 45 58 PM](https://github.com/senlin/classic-editor-addon/assets/141756083/f5e4c1ee-2a63-4863-b5af-e4541fe8f092)

**Comment by senlin** [comment]
As you can see from the below screenshot, I cannot reproduce the issue.

What are the plugins you have installed and which PHP version is your site running?

![20230816-Image-0w1di](https://github.com/senlin/classic-editor-addon/assets/650066/51322e24-0a8d-4089-be56-ba26025e6292)

**Comment by supportTheArtblog** [comment]
I went through my plugins and apparently 3D FlipBook - Lite Edition - was the culprit/winner? I've deactivated it and will reach out to them. Your plugin seems to be working. Thanks so much.
