### ISSUE TITLE
Editor CSS

### ISSUE THREAD

**Issue by craigbass76** [senlin/classic-editor-addon#19]
Is there a css file I can edit somewhere that affects the editor itself? I've got a couple things I'll be doing on the live side of the site, and a novice blogger helping me, so I want to try to mirror those couple of styles (h5 and h6 size and colors) if it's possible.

I did try `wp-includes/css/editor.min.css` and `wp-includes/js/tinymce/skins/wordpress/wp-content.css`, but had no luck.

**Comment by senlin** [comment]
Hello Craig,

The plugin "merely" brings back the Classic Editor, which you can see if you look in the [source code](https://github.com/senlin/classic-editor-addon/blob/master/classic-editor-addon.php).

To adjust styling of the editor itself you would need to look into a plugin that alters TinyMCE, such as [this one](https://wordpress.org/plugins/tinymce-custom-styles/).

Hope that helps.
