### ISSUE TITLE
Adding a Button

### ISSUE THREAD

**Issue by craigbass76** [senlin/classic-editor-addon#20]
Is it possible to add a button to the editor so that I can insert a special div (a lot)? I think if I can see where the other buttons are, I can figure it out from there. ANything I'm finding online is block-based though, or very old. (class-wp-edit.php references and such).

**Comment by senlin** [comment]
Hello Craig,

Sure it's possible to add a button to the editor.

However that has nothing to do with the Classic Editor + plugin, which only brings back the Classic Editor.

In the past I developed a plugin that used the hidden but available styles dropdown menu to add classes to it. The plugin is archived, but [publicly available](https://github.com/senlin/so-responsive-content/tree/master), which might help you on your way.

Another good resource that can help is the [TinyMCE Custom Styles article in the WP Codex](https://codex.wordpress.org/TinyMCE_Custom_Styles).

Hope that helps, good luck!
Pieter

**Comment by craigbass76** [comment]
Thanks, man. I wasn't sure if TinyMCE was under the hood, or the real old FCKeditor. I gave up hunting and asked you.
