### ISSUE TITLE
Auto refresh plugins page after installation/activation of "Classic Editor" plugin

### ISSUE THREAD

**Issue by senlin** [senlin/classic-editor-addon#4]
reported via [review](https://wordpress.org/support/topic/another-go-to-plugin/):

> If you add/install/activate your plugin without first installing the “Classic Editor” plugin, your plugin provides the “Install Now” link – which is excellent. However, once it has installed/activated “Classic Editor” via this link, it does not refresh the list of plugins – hence it does not look as though “Classic Editor” has been installed & activated. You have to then refresh the plugins page to show it in the list.

**Comment by senlin** [comment]
@gschoppe - do you know how to add this to our plugin?

**Comment by gschoppe** [comment]
@senlin Unfortunately, I can't think of a trivial way to add this functionality without forking and modifying the code for wp-dependency-installer, which isn't ideal.

I think the correct path is to push this issue upstream to that repository and suggest an enhancement that triggers an automatic refresh when the admin notice is activated on the plugins page.

**Comment by senlin** [comment]
@gschoppe - Thanks for looking into this, will kick it upstream then.

**Comment by senlin** [comment]
"fixed" issue with workaround in 2.3.0
