### ISSUE TITLE
Enhancement: remove wp block library css

### ISSUE THREAD

**Issue by mitchelldmiller** [senlin/classic-editor-addon#5]
Hello:
WP started adding "block library css" to documents.
AFAIK it is only used with a Gutenberg video or image block.

I started adding `wp_dequeue_style('wp-block-library');` to sites without Gutenberg.

Should this plugin remove unused block CSS?

**Comment by senlin** [comment]
Thanks for the suggestion.

> I started adding wp_dequeue_style('wp-block-library'); to sites without Gutenberg.

This in itself doesn't do anything, but I will have a look to make it do something :)

**Comment by senlin** [comment]
@mitchelldmiller 
here you go: https://github.com/senlin/classic-editor-addon/releases/tag/v2.4.0
