### ISSUE TITLE
Block react from loading in front end

### ISSUE THREAD

**Issue by scottbuscemi** [senlin/classic-editor-addon#6]
It'd be be great if this also blocked the vendor script of react from loading as well. Thanks!

**Comment by scottbuscemi** [comment]
Update: it seems to be a specific site that's doing this, so it must be plugin related...

**Comment by senlin** [comment]
thanks for the update @scottbuscemi 
I will be closing this issue now then, but it would be nice if you can update it with the name of the plugin that was causing the "conflict", if only to help other people with the same issue.
