### ISSUE TITLE
Wordpress 5.3 Upgrade Seems To Have Caused PHP Compatibility Problems

### ISSUE THREAD

**Issue by NetJon** [senlin/classic-editor-addon#7]
When my site was upgraded to Wordpress 5.3 the site broke (php errors at the top referring to the classic editor addon plugin).

I was unable to login to the admin area at all.

My hosting provider helped me out and solved the problem by rolling back the PHP to 5.6.

I switched the PHP back to 7.1 and the errors returned.

I have simply de-activated the plugin for now to solve my problem.  

Others are also having this problem and describing it here:  https://wordpress.org/support/topic/wordpress-v5-3-errors/

**Comment by senlin** [comment]
Thank you for reporting this, we have [released an update](https://github.com/senlin/classic-editor-addon/releases/tag/v2.6.0) which fixes this issue.
