### ISSUE TITLE
Classic Editor Addon 2.6.4 conflicts with FluentSMTP 2.1.0

### ISSUE THREAD

**Issue by disgruntledusername** [senlin/classic-editor-addon#8]
After upgrade of CEA, FluentSMTP shows error at top of admin pages:

The FluentSMTP plugin depends on wp_mail pluggable function and plugin is not able to extend it. Please check if another plugin is using this and disable it for FluentSMTP to work!

Possible Conflict: /*Path_to*/wp-includes/pluggable.php:182

**Comment by senlin** [comment]
Hi, the only thing that is changed in the 2.6.4 version is the updated WP Dependency Installer library, so I don't think that your current conflict is related?

**Comment by disgruntledusername** [comment]
Yeah, it's a weird scenario. I believe I only updated this plugin and then the error appeared. Didn't notice it right away and was multi-tasking on multiple sites though. But, going from memory, I disabled this plugin version and the error cleared. Re-enabled this plugin version and it re-appeared. I'm using the free version of Fluent SMTP, you can check if you'd like or let me know if I can provide anything else.

**Comment by disgruntledusername** [comment]
Just rolled back CEA to 2.6.3 with WP Rollback...no errors. Definitely a problem introduced in latest revision.

**Comment by senlin** [comment]
I installed the FluentSMTP plugin on a dev install and indeed the notice shows there too. I had a look through the updated library, but cannot find anything related to the `wp_mail` function.

> Just rolled back CEA to 2.6.3 with WP Rollback...no errors

Rolling back the update of CEA is **not an option** I'm afraid as it fixed a security issue.

From the WP Plugins Security team:
> The previous version of the wp-dependency-installer library (https://github.com/afragen/wp-dependency-installer) which was installed on CEA 2.6.3, is known to be affected by security issues (low privilege users being able to activate any plugin, as well as attackers being able to make a logged in admin install plugins from the wp-dependencies.json via a CSRF attack). 

I then tried installing several other SMTP plugins and none of them show any sign of a conflict. Could it be that there is something in the FluentSMTP plugin that is conflicting?

**Comment by disgruntledusername** [comment]
I happened to have WP Mail SMTP handy and activating it didn't produce any error as well.

I'll ping the WPManageNinja team and see if they can take a look.

Thank you for the quick response and taking a look!

**Comment by disgruntledusername** [comment]
ps: I'll point them here since this thread explains the issue and our troubleshooting results, if you don't mind keeping it up for a little bit..

**Comment by senlin** [comment]
Yeah no worries, I will keep it open for now.

**Comment by senlin** [comment]
I have released v3.0.0 that solves the conflicts (replaced the library with a simple dependency check/notice); will close this issue now, but you will be able to find it under the [closed issues] tab.
